apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opa_kecloak_middleware.fullname" . }}
  labels:
    {{- include "opa_kecloak_middleware.labels" . | nindent 4 }}
data:
  FASTAPI_PORT: {{ .Values.service.port }}
  FASTAPI_NUM_WORKERS: {{ .Values.middlewareConfig.fastapiNumWorkers }}
{{- if .Values.middlewareConfig.appRootPath}}
  APP_ROOT_PATH: {{ .Values.middlewareConfig.appRootPath }}
{{- end }}