{{- if not .Values.middlewareConfig.secretConfigName}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opa_kecloak_middleware.fullname" . }}
  labels:
    {{- include "opa_kecloak_middleware.labels" . | nindent 4 }}
data:
  API_KEY: {{ .Values.middlewareConfig.apiKey | b64enc }}
  KEYCLOAK_SERVER_URL: {{ .Values.middlewareConfig.keycloak.serverUrl | b64enc }}
  KEYCLOAK_REALM_NAME: {{ .Values.middlewareConfig.keycloak.realmName | b64enc }}
  KEYCLOAK_CLIENT_ID: {{ .Values.middlewareConfig.keycloak.clientId | b64enc }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.middlewareConfig.keycloak.clientSecret | b64enc }}
  KEYCLOAK_GRANT_TYPE: {{ .Values.middlewareConfig.keycloak.grantType | b64enc }}
{{- if .Values.middlewareConfig.keycloak.grantType | eq "password" }}
  KEYCLOAK_USERNAME: {{ .Values.middlewareConfig.keycloak.username | b64enc }}
  KEYCLOAK_PASSWORD: {{ .Values.middlewareConfig.keycloak.password | b64enc }}
{{- end }}
{{- end }}